# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuRGMbPgYZECyoQ5YbdPpdVwHf-RXydA
"""

!pip install  -q -U google-genai

import google.generativeai as genai
from google.colab import userdata

# Configure the Gemini API with the API key from Colab secrets
genai.configure(api_key=userdata.get('GEMINI_API_KEYS'))

for m in genai.list_models():
  print(m.name)

import google.generativeai as genai

model = genai.GenerativeModel(
    model_name='gemini-3.5-flash-lite',
    system_instruction='you are a helpful assistant'
)

response = model.generate_content(
    contents='tell me one line of joke about developers.', #user prompts
    generation_config={
        'temperature': 0.5,
        'max_output_tokens': 200,
        # 'thinking_config' is not a recognized parameter for generation_config
    }
)


print("text generated by AI:",response.text)

print()
u = response.usage_metadata

print("usage", response.usage_metadata)



print("")

print("prompt_token_count", u.prompt_token_count)
print('candidates_token_count', u.candidates_token_count)

print('total_token_count', u.total_token_count)
print()
print()

import google.generativeai as genai
from google.colab import userdata

# Configure the Gemini API with the API key from Colab secrets
genai.configure(api_key=userdata.get('GEMINI_API_KEYS'))

MODEL_NAME = 'gemini-3.5-flash-lite'

# Initialize the model with system instruction
model = genai.GenerativeModel(
    model_name=MODEL_NAME,
    system_instruction='you are a creative story writing assistant'
)

def generate_story(topic, genre, length_word=200):
    prompt = f"Write a {genre} story about {topic} in around {length_word} words."

    response = model.generate_content(
        contents=prompt,
        generation_config={
            'temperature': 1,
            'max_output_tokens': 500,
        }
    )

    print("Story generated by AI:", response.text)

    print()
    u = response.usage_metadata

    print("usage", response.usage_metadata)

    print("")

    print("prompt_token_count", u.prompt_token_count)
    print('candidates_token_count', u.candidates_token_count)

    print('total_token_count', u.total_token_count)
    print()
    print()




topic = input("Enter a topic for the story: ")
genre = input("Enter a genre for the story: ")

generate_story(topic, genre)